### ISSUE TITLE
Build mirror app to another folder but from the same source

### ISSUE THREAD

**Issue by ghost** [meteor-velocity/meteor#1]
When starting a mirror, the same app files should be used as source.
But the output (.meteor/local) should be another folder.
This allows to include test files without overwriting the main app build.
The benefit of using the same app source is that we get auto restarts and don't need to synchronize the copy of the mirror.

`meteor --test-packages` already does something similar. I think we can reuse it :-)

**Comment by SamHatoum** [comment]
:+1: 

This would also open up the ability to instrument the code in the other folder
