### ISSUE TITLE
meteor --test sets an environment var

### ISSUE THREAD

**Issue by SamHatoum** [meteor-velocity/meteor#2]
As a framework author
I need to know if a user is running in `meteor --test` mode
So that I can customize the development vs CI experience

**Comment by ghost** [comment]
:+1:

**Comment by ghost** [comment]
It will be `VELOCITY_CI=1`. Documented in https://github.com/meteor-velocity/velocity/blob/develop/ENVIRONMENT_VARIABLES.md#velocity_ci.

**Comment by ghost** [comment]
A question:
- Should the tests not run in the CI mode when  the user runs its tests with `meteor --test` while developing?
- @samhatoum How is the CI mode different from the developing mode in your case?

**Comment by SamHatoum** [comment]
--test should always let the framework know it's in CI mode, wherever it is run. For my use case anyway, which is:

In meteor run mode, I want to run only cucumber tests with a specific tag. In meteor --test mode, I want to run all tags (except @ignore).

**Comment by queso** [comment]
I look at Rails and it’s conventions for something like this.  NODE_ENV is already set to production when running in prod. What if it was just change to test while running in —test mode?

--Josh Owens | 513-678-7081 | http://joshowens.me | @joshowens

**Comment by ghost** [comment]
> I look at Rails and it’s conventions for something like this. NODE_ENV is already set to production when running in prod. What if it was just change to test while running in —test mode?

Technically we cannot use NODE_ENV because Meteor always sets it to development ;-)

For Sams use case its important to distinguish between the CI mode where no human runs the tests and between development mode where a human runs the tests.

**Comment by SamHatoum** [comment]
I like the environment idea as a general already for more than just
development and production options, shame it can't happen technically.

As for my specific use case, it's that I want to know if meteor will shut
down after the tests run or if it will stay watching. This behaviour
happens to be synonymous with CI

**Comment by SamHatoum** [comment]
@Sanjo is this still open? I could swear I saw it working at once time!

**Comment by ghost** [comment]
This is implemented in the latest release. To make it work, you need to start the test running with the latest Velocity release of Meteor. Currently this is:

```
meteor --test --release velocity:METEOR@1.1.0.2_3
```

This should be added to the READMEs of the testing frameworks @rissem @samhatoum @rjsmith @logankoester

Here is how I have done it for sanjo:jasmine: https://github.com/Sanjo/meteor-jasmine#running-tests-in-continuous-integration
